services:

  django-app:
    build: fastr_project
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
      - smtp-server
    command: bash -c '
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000'

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  celery:
    build: fastr_project
    restart: always
    command: celery -A fastr worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - django-app
      - postgres
      - redis
      - smtp 

  redis:
    image: redis 

  smtp-server:
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'
    ports:
      - 8025:8025

volumes:
  postgres_data:
